### ISSUE TITLE
updateVertexPosition: Why the bitwise OR ( | ) in the update equation?

### ISSUE THREAD

**Issue by PeterVeltman** [bldeng/GuidedDenoising#1]
I am checking your nice program. While going over the code to test some different algorithm, I found the following equation:
`temp_point += temp_normal * (temp_normal | (temp_centroid - p));`

should this be changed to:
`temp_point += temp_normal * (temp_normal * (temp_centroid - p));`

In your paper, this is also done in equation (6) on page 5.

Changing the equation gives much nicer results for my application :).

**Comment by bldeng** [comment]
In OpenMesh, operator | is overloaded for dot product between vectors. So it is correct to use | here.
