### ISSUE TITLE
Hello. I have a question from your Guided Denoising QT.

### ISSUE THREAD

**Issue by star4s** [bldeng/GuidedDenoising#3]
Hello. I am studying about mesh denoising, and I am interested in your study about Guided Denoising.
 I have a question in your Guided Denoising QT.
I followed your instrtuction for running ther QT program.
After I open the file src/MeshDenoising.pro with QtCreator and build the source code,
After MeshDenoising.exe_manifest.rc built
I got a link error, "C++ Qt Linker Error 1104: Сannot open file 'MeshDenoising.exe.embed.manifest' ".
I am using Qt_5_3_MSVC2013_OpenGL_32bit.
How can I build the QT program?
I need your help.
Thank you for your attention.

**Comment by bldeng** [comment]
To help us diagnose the problem, could you please post the whole output of the compilation process?

**Comment by star4s** [comment]
Thank you for your answer.
I need your help.
I posted my processing in the other section.
Could you check what problem is, please?
