### ISSUE TITLE
This is my Process for your QT program.

### ISSUE THREAD

**Issue by star4s** [bldeng/GuidedDenoising#4]
1. MeshDenoising.pro was opened by the QT Creator (4.5.1).
2. In the QT Creator,
![1](https://user-images.githubusercontent.com/25783167/36409248-4ac18972-1602-11e8-931e-89f8694bab97.jpg)

I clicked "Configure Project".

3.  
![2](https://user-images.githubusercontent.com/25783167/36409307-acdbd39c-1602-11e8-9a0b-032d08733c1f.jpg)

I was build.

4. I have a error message on the screen.

![3](https://user-images.githubusercontent.com/25783167/36409344-f2e9d1fe-1602-11e8-85db-d1220c767257.jpg)

5. This is my Build Settings

![4](https://user-images.githubusercontent.com/25783167/36409370-1cec17be-1603-11e8-914d-416cedf0c765.jpg)

![5](https://user-images.githubusercontent.com/25783167/36409426-6800c3f8-1603-11e8-96cb-3253d5ebb18f.jpg)
![6](https://user-images.githubusercontent.com/25783167/36409428-68319154-1603-11e8-8978-f4c98cdc78a4.jpg)
![7](https://user-images.githubusercontent.com/25783167/36409429-685e09a0-1603-11e8-8754-079aa0dd4792.jpg)

**Comment by bldeng** [comment]
Could you please also post the compiler output when you build the program?
