### ISSUE TITLE
关于构建项目后出现的问题

### ISSUE THREAD

**Issue by Jacklwln** [bldeng/GuidedDenoising#8]
您好！我按照您的README文件的内容安装了QT5.3, 打开MeshDenoising.pro，但是在构建后出现：
error: C:/Users/anna/Desktop/GuidedDenoising/GuidedDenoising-5cba257fe359601a18245e5749cfc5b93616efe8/build-MeshDenoising-Desktop_Qt_5_3_MinGW_32bit-Debug/Denoising/../OpenMesh/OpenMesh.lib: No such file or directory

这个怎么解决呢？

**Comment by bldeng** [comment]
README 文件中提到代码在以下环境中测试通过:
- Windows 10 with Qt 5.11.2, Qt Creator 4.7.1, and MSVC 2017 Community Edition (older versions of MSVC may not work)

根据您的描述，您使用的是 QT 5.3 和 MinGW 编译器。我们没有测试过这个组合，不确定能否成功编译。请先按照 README 文件中的配置环境编译？

**Comment by Jacklwln** [comment]
好的，谢谢啦！
